version: "3.8"

services:
  back-end:
    build:
      context: ./src/back-end/
    ports:
      - '127.0.0.1:8081:80'

  front-end:
    build:
      context: ./src/front-end/
    depends_on:
      - back-end
    ports:
      - '127.0.0.1:8080:80'
